Repository FuelLabs/sway-nightly-binaries, pull requests merged in 2024-11, with the labels that each got.

#55 fix: add missing `forc-submit` to list of released binaries
  .github/workflows/nightly-forc-release.yml
Labels: bug

#56 chore: add tooling as codeowners for the repo
  .github/CODEOWNERS
Labels: enhancement

#53 chore: swap deprecated actions/upload-release-assets to softprops/action-gh-release
  .github/workflows/create-release.yml
  .github/workflows/nightly-forc-explorer-release.yml
  .github/workflows/nightly-forc-release.yml
  .github/workflows/nightly-forc-wallet-release.yml
  .github/workflows/nightly-fuel-core-release.yml
Labels: bug, ci

#57 chore: use rust v1.79.0 while building fuel-core
  .github/workflows/nightly-fuel-core-release.yml
Labels: ci

#58 Nightly jobs are performed on master
  .github/workflows/nightly-forc-explorer-release.yml
  .github/workflows/nightly-forc-release.yml
  .github/workflows/nightly-forc-wallet-release.yml
  .github/workflows/nightly-fuel-core-release.yml
Labels: bug, ci

#59 Checkout the tag on release
  .github/workflows/nightly-forc-explorer-release.yml
  .github/workflows/nightly-forc-release.yml
  .github/workflows/nightly-forc-wallet-release.yml
  .github/workflows/nightly-fuel-core-release.yml
Labels: bug, ci

#60 Enforce git tag on master releases
  .github/workflows/nightly-forc-explorer-release.yml
  .github/workflows/nightly-forc-release.yml
  .github/workflows/nightly-forc-wallet-release.yml
  .github/workflows/nightly-fuel-core-release.yml
Labels: bug, ci

#61 Create tag on repo, push to release from other repos
  .github/workflows/create-release.yml
  .github/workflows/nightly-forc-explorer-release.yml
  .github/workflows/nightly-forc-release.yml
  .github/workflows/nightly-forc-wallet-release.yml
  .github/workflows/nightly-fuel-core-release.yml
Labels: bug, ci

#62 Incorrect job output referenced
  .github/workflows/create-release.yml
Labels: bug, ci

#63 Remove master tag now correct release name is used
  .github/workflows/create-release.yml
  .github/workflows/nightly-forc-explorer-release.yml
  .github/workflows/nightly-forc-release.yml
  .github/workflows/nightly-forc-wallet-release.yml
  .github/workflows/nightly-fuel-core-release.yml
Labels: bug, ci
